### ISSUE TITLE
TypeError: Cannot read property 'place' of undefined

### ISSUE THREAD

**Issue by gnerd** [microsoftgraph/nodejs-webhooks-rest-sample#153]
I pretty much followed the instructions and I get this error when I click create a subscription using app-only authentication
TypeError: Cannot read property 'replace' of undefined
   at Authority.replaceTenant (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\src\authority\Authority.ts:151:26)
   at Authority.get [as tokenEndpoint] (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\src\authority\Authority.ts:110:25)
   at ClientCredentialClient.<anonymous> (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\src\client\ClientCredentialClient.ts:101:74)
   at step (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\dist\index.js:78:23)
   at Object.next (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\dist\index.js:59:53)
   at C:\temp\dotnet\webhook\node_modules\@azure\msal-common\dist\index.js:52:71
   at new Promise (<anonymous>)
   at __awaiter (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\dist\index.js:48:12)
   at ClientCredentialClient.executeTokenRequest (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\dist\index.js:5218:16)
   at ClientCredentialClient.<anonymous> (C:\temp\dotnet\webhook\node_modules\@azure\msal-common\src\client\ClientCredentialClient.ts:46:31)

**Comment by gnerd** [comment]
wrong tenantID
