### ISSUE TITLE
Cannot read property 'certificate' of undefined

### ISSUE THREAD

**Issue by gnerd** [microsoftgraph/nodejs-webhooks-rest-sample#154]
I select from the main webpage - 'create subscription using app-only authentication' 

(node:12484) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'certificate' of undefined
    at C:\temp\dotnet\webhook\helpers\/certificateHelper.js:19:47
    at C:\temp\dotnet\webhook\node_modules\pem\lib\pem.js:319:16
    at C:\temp\dotnet\webhook\node_modules\pem\lib\pem.js:211:16
    at done (C:\temp\dotnet\webhook\node_modules\pem\lib\pem.js:80:16)
    at C:\temp\dotnet\webhook\node_modules\pem\lib\pem.js:87:7
    at deleteSeries (C:\temp\dotnet\webhook\node_modules\pem\lib\helper.js:130:14)
    at Object.module.exports.deleteTempFiles (C:\temp\dotnet\webhook\node_modules\pem\lib\helper.js:133:3)
    at C:\temp\dotnet\webhook\node_modules\pem\lib\pem.js:86:12
    at C:\temp\dotnet\webhook\node_modules\pem\lib\openssl.js:57:14
    at C:\temp\dotnet\webhook\node_modules\pem\lib\openssl.js:222:7
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:12484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by baywet** [comment]
Thanks for reaching out. It looks like the helper wasn't able to [create the self-signed](https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/master/helpers/certificateHelper.js#L19) certificate used to encrypt/decrypt the rich notifications payload. Can you double check open-ssl is installed on the machine you are running this code on?

**Comment by gnerd** [comment]
i did not have opensll - after installing that, i get a different error.  Should I close this and open a new issue? (new to github)
Error: Azure Active Directory workload is not enabled for rich notifications.
    at new GraphError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:59:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:62:18)
    at Function.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:89:31)
    at step (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:122:57)
    at C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:111:16)
    at Function.GraphErrorHandler.getError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:386:55)

**Comment by baywet** [comment]
Identity objects do not support rich notifications today, see [this table](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta) for reference. You need to set `IncludeResourceData` to `false` or try another resource (chat/channel messages or presence). As we solved the original issue, I'm going to go ahead an close this issue.
