### ISSUE TITLE
 Notification endpoint must respond with 200 OK to validation request.

### ISSUE THREAD

**Issue by gnerd** [microsoftgraph/nodejs-webhooks-rest-sample#158]
I turned off the 'includeresourcedata' and now I get this
rror: Subscription validation request failed. Notification endpoint must respond with 200 OK to validation request.
    at new GraphError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:59:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:62:18)
    at Function.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:89:31)
    at step (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:122:57)
    at C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:111:16)
    at Function.GraphErrorHandler.getError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:386:55)

**Comment by baywet** [comment]
Have you exposed via application via ngrok and updated the URL in the constants?

**Comment by gnerd** [comment]
Yes in ngrok inspect I see this

HTTP/1.1 404 Not Found
X-Powered-By: Express
X-RateLimit-Limit: 2400
X-RateLimit-Remaining: 2399
Date: Wed, 09 Dec 2020 00:21:16 GMT
X-RateLimit-Reset: 1607473290
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 927
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Not Found<br> &nbsp; &nbsp;at C:\temp\dotnet\webhook\/app.js:37:13<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\temp\dotnet\webhook\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:317:13)<br> &nbsp; &nbsp;at C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:335:12)<br> &nbsp; &nbsp;at next (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:275:10)<br> &nbsp; &nbsp;at C:\temp\dotnet\webhook\node_modules\express-rate-limit\lib\express-rate-limit.js:154:15<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:93:5)</pre>
</body>
</html>

**Comment by baywet** [comment]
What's the url you setup? what's the URL ngork is trying to get to? was local port are you exposing?

**Comment by gnerd** [comment]
Forwarding                    http://6666d37d425c.ngrok.io -> http://localhost:3000                                    
 Forwarding                    https://6666d37d425c.ngrok.io -> http://localhost:3000    



C:\temp\dotnet\webhook>npm start

> microsoft-graph-webhook-nodejs@1.0.0 start C:\temp\dotnet\webhook
> mocha ./tests/confTest.js && babel-node --config-file ./babel.config.json ./index



  MSAL
    √ Checking clientID, clientSecret and tenantID in constants.js

  NotificationURL
    √ Checking notificationUrl in constants.js


  2 passing (8ms)

Express server listening on port 3000
GET / 304 6.140 ms - -
GET /callbackapponly 400 2138.953 ms - 1378
Error: Azure Active Directory workload is not enabled for rich notifications.
    at new GraphError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:59:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:62:18)
    at Function.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:89:31)
    at step (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:122:57)
    at C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:111:16)
    at Function.GraphErrorHandler.getError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:386:55)
Terminate batch job (Y/N)? y

C:\temp\dotnet\webhook>npm start

> microsoft-graph-webhook-nodejs@1.0.0 start C:\temp\dotnet\webhook
> mocha ./tests/confTest.js && babel-node --config-file ./babel.config.json ./index



  MSAL
    √ Checking clientID, clientSecret and tenantID in constants.js

  NotificationURL
    √ Checking notificationUrl in constants.js


  2 passing (8ms)

Express server listening on port 3000
POST /?validationToken=Validation%3a+Testing+client+application+reachability+for+subscription+Request-Id%3a+9d3b1460-659e-a627-b3bd-ce3465d57f91 404 55.971 ms - 927
Error: Not Found
    at C:\temp\dotnet\webhook\/app.js:37:13
    at Layer.handle [as handle_request] (C:\temp\dotnet\webhook\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:317:13)
    at C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:335:12)
    at next (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:275:10)
    at C:\temp\dotnet\webhook\node_modules\express-rate-limit\lib\express-rate-limit.js:154:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
GET /callbackapponly 400 1540.863 ms - 1417
Error: Subscription validation request failed. Notification endpoint must respond with 200 OK to validation request.
    at new GraphError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:59:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:62:18)
    at Function.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:89:31)
    at step (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:122:57)
    at C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:111:16)
    at Function.GraphErrorHandler.getError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:386:55)
POST /?validationToken=Validation%3a+Testing+client+application+reachability+for+subscription+Request-Id%3a+783beb96-5b8f-ee7a-7aff-c8958e276549 404 3.735 ms - 927
Error: Not Found
    at C:\temp\dotnet\webhook\/app.js:37:13
    at Layer.handle [as handle_request] (C:\temp\dotnet\webhook\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:317:13)
    at C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:335:12)
    at next (C:\temp\dotnet\webhook\node_modules\express\lib\router\index.js:275:10)
    at C:\temp\dotnet\webhook\node_modules\express-rate-limit\lib\express-rate-limit.js:154:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
GET /callbackapponly 400 1258.017 ms - 1417
Error: Subscription validation request failed. Notification endpoint must respond with 200 OK to validation request.
    at new GraphError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:59:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:62:18)
    at Function.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:89:31)
    at step (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:122:57)
    at C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\temp\dotnet\webhook\node_modules\tslib\tslib.js:111:16)
    at Function.GraphErrorHandler.getError (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (C:\temp\dotnet\webhook\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:386:55)


constants.js
exports.subscriptionConfiguration = {
  changeType: 'updated',
  notificationUrl: 'https://6666d37d425c.ngrok.io',
  resource: '/groups/fc39cb3a-6652-421e-a9ba-3c252d44495d',
  clientState: 'cLIENTsTATEfORvALIDATION',
  includeResourceData: false
};

**Comment by baywet** [comment]
your notification URL should look like this `https://92f5927a0659.ngrok.io/listen` (ending with `/listen`)

**Comment by gnerd** [comment]
Fantastic - I left that off based on some other testing I was doing, its all working now.  Awesome solution!

**Comment by baywet** [comment]
Glad I could help. Don't hesitate to let us know what we could improve in the getting started documentation to make using this sample easier.
