### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END on subscription creation (/listen)

### ISSUE THREAD

**Issue by gnerd** [microsoftgraph/nodejs-webhooks-rest-sample#160]
Sorry - still hitting an issue, and the subscription does not actually get created. 

I see it posting back now (in ngrok)

POST /listen?validationToken=Validation%3a+Testing+client+application+reachability+for+subscription+Request-Id%3a+70d77e72-0725-bd6c-2ec5-e8a03f84257a HTTP/1.1
Host: localhost:3000
Content-Length: 0
Accept-Encoding: gzip
Content-Type: text/plain; charset=utf-8
X-Forwarded-For: 13.85.192.123
X-Forwarded-Proto: https
X-Original-Host: 6666d37d425c.ngrok.io

but then NPM dies

Express server listening on port 3000
GET / 304 3.022 ms - -
POST /listen?validationToken=Validation%3a+Testing+client+application+reachability+for+subscription+Request-Id%3a+38ef101b-fa0f-ca42-b0d8-498fdee9aa15 200 9.538 ms - 117
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:788:7)
    at _callee$ (C:\temp\dotnet\webhook\routes\/listen.js:83:22)
    at tryCatch (C:\temp\dotnet\webhook\node_modules\@azure\msal-node\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\temp\dotnet\webhook\node_modules\@azure\msal-node\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\temp\dotnet\webhook\node_modules\@azure\msal-node\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\temp\dotnet\webhook\routes\listen.js:28:103)
    at _next (C:\temp\dotnet\webhook\routes\listen.js:30:194)
    at C:\temp\dotnet\webhook\routes\listen.js:30:364
    at new Promise (<anonymous>)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:727:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microsoft-graph-webhook-nodejs@1.0.0 start: `mocha ./tests/confTest.js && babel-node --config-file ./babel.config.json ./index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microsoft-graph-webhook-nodejs@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jrosen\AppData\Roaming\npm-cache\_logs\2020-12-09T16_37_32_060Z-debug.log

**Comment by baywet** [comment]
This stack trace indicates an error with msal node (the authentication library). I would encourage you to double check your application registration and your settings (in the constants). If you still run into the issue, you might want to cross-pross in their repo instead https://github.com/AzureAD/microsoft-authentication-library-for-js

**Comment by baywet** [comment]
Closing due to inactivity.

**Comment by philjones88** [comment]
@baywet it's caused by this line:

https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/main/routes/listen.js#L83

changing it to just `res.status(status);` fixed this exact issue for me.

**Comment by baywet** [comment]
@philjones88 
thanks for sharing this information. I recently ran into a similar issue and just authored a pull request to fix that. see #233 
Not calling the end method leaves the http stream open, which makes the notification service wait, time out and eventually retry. You don't want that in production.
Calling it with an http status code however, forcibly closes the stream, which makes any interception which hasn't completed (azure-identity) throw.
Calling end without a status code, closes the stream when the interceptors are completed, which solves both issues.
