### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by Yogi6596** [microsoftgraph/nodejs-webhooks-rest-sample#236]
Hi,
I am trying to run sample webhook code and I am able to create subscription. Then I made some changes in Microsoft teams. Now I am getting socket error. Please refer attached block of error. I request you to please help me out.

GET /socket.io/?EIO=4&transport=polling&t=NX5xPls 404 1.903 ms - 1338
Error: Not Found
    at /home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/app.js:37:13
    at Layer.handle [as handle_request] (/home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/node_modules/express/lib/router/index.js:317:13)
    at /home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/node_modules/express/lib/router/index.js:275:10)
    at /home/nodejs-webhooks-rest-sample-main/nodejs-webhooks-rest-sample-main/node_modules/express-rate-limit/lib/express-rate-limit.js:154:15

**Comment by Jumaodhiss** [comment]
@Yogi6596 please share your subscription payload. This looks like you want the notifications to be delivered through web sockets
